name: Build and Deploy
on:
    # Runs on pull requests
    pull_request:
        branches: ["*"]
    # Runs on pushes to main
    push:
        branches: ["main"]
    # Runs on demand
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: oscarlevin/pretext:full

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: install deps
              run: pip install -r requirements.txt

            - name: build checkit
              run: python scripts/bank/build.py

            - name: build web-student
              run: pretext build web-student
            - name: build print-student
              run: pretext build web-instructor
            - name: build web-instructor
              run: pretext build web
            - name: build print-instructor
              run: pretext build print-instructor
            - name: build slides
              run: pretext build slides
            - name: stage builds
              run: pretext deploy --stage-only

            - name: Bundle output/stage as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deploy
                  path: output/stage

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: precalculus-beta-20240616
                  directory: deploy
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
