name: Build and Deploy to Github Pages
on:
    # Runs both on pull requests and when a pull request is merged.
    push:
        branches: ["main"]
    pull_request:
        branches: ["*"]

jobs:
    # This job builds the book. You can download the resulting build "artifact" by
    # navigating to your actions manager in Github, selecting this run, and clicking
    # "download artifact" on the "website" artifact.
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Build with PreTeXt
              uses: siefkenj/pretext-build-action@main
              with:
                  project-root: "."
                  output-dir: "."

            - name: Bundle output/web as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: website
                  path: output/web

    # This job deploys the artifact built in the previous job to Github pages.
    deploy:
        runs-on: ubuntu-latest
        # only deploy to github pages if we have merged into main or master
        if: github.event_name == 'push' &&  github.ref == 'refs/heads/main'
        needs: build
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: "page"
            cancel-in-progress: false
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download website artifact
              uses: actions/download-artifact@v4
              with:
                  name: website
                  path: website
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./website"
            - name: Deploy to Github Pages
              id: deployment
              uses: actions/deploy-pages@v4