name: Test Build
on:
    # Runs on pull requests
    pull_request:
        branches: ["*"]

jobs:
    # This job builds the book. You can download the resulting build "artifact" by
    # navigating to your actions manager in Github, selecting this run, and clicking
    # "download artifact" on the "website" artifact.
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: run checkit
              run: python scripts/bank/build.py

            # - name: Build student web version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build web-student
            #       project-root: "."
            #       output-dir: "."

            # - name: Build student print version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build print-student
            #       project-root: "."
            #       output-dir: "."

            # - name: Build instructor web version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build web
            #       project-root: "."
            #       output-dir: "."
                  
            # - name: Build instructor print version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build print-instructor
            #       project-root: "."
            #       output-dir: "."

            # - name: Build slides with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build slides
            #       project-root: "."
            #       output-dir: "."

            - name: Stage with PreTeXt
              uses: siefkenj/pretext-build-action@main
              with:
                  pretext-command: deploy --stage-only
                  project-root: "."
                  output-dir: "."

            - name: Bundle output/stage as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: website
                  path: output/stage

            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: precalculus-beta-20240616
                  directory: output/stage
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
