name: Test and Deploy
on:
    # Runs on pull requests
    pull_request:
        branches: ["*"]
jobs:
    build:
        runs-on: ubuntu-latest
        container: oscarlevin/pretext:full

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: install deps
              run: |
                pip install -r requirements.txt

            - name: run checkit
              run: |
                python scripts/bank/build.py

            # - name: Build student web version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build web-student
            #       project-root: "."
            #       output-dir: "."

            # - name: Build student print version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build print-student
            #       project-root: "."
            #       output-dir: "."

            # - name: Build instructor web version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build web
            #       project-root: "."
            #       output-dir: "."
                  
            # - name: Build instructor print version with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build print-instructor
            #       project-root: "."
            #       output-dir: "."

            # - name: Build slides with PreTeXt
            #   uses: siefkenj/pretext-build-action@main
            #   with:
            #       pretext-command: build slides
            #       project-root: "."
            #       output-dir: "."

            - name: Stage with PreTeXt
              uses: siefkenj/pretext-build-action@main
              with:
                  pretext-command: deploy --stage-only
                  project-root: "."
                  output-dir: "."

            - name: Bundle output/stage as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: website
                  path: output/stage
    deploy:
        runs-on: ubuntu-latest

            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: precalculus-beta-20240616
                  directory: output/stage
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
